services:
  web:
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.webhook
    restart: always
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./entrypoints/webhook_entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - db
      - redis
      - base
